name: Developer

on:
  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/setup-node@v2.5.0
      - name: Setup
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
